-- Code generated by modulegen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS `departments` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `manager` VARCHAR(255) NULL,
  `status` INT NOT NULL,
  `created_at` DATETIME(3) NULL,
  `updated_at` DATETIME(3) NULL
);

INSERT INTO `menus` (`parent_id`, `name`, `menu_type`, `path`, `component`, `perms`, `sort`, `status`, `created_at`, `updated_at`)
SELECT 0, '部门管理（生成）', 'menu', '/generated/department', '', 'department:list', 900, 1, NOW(3), NOW(3)
WHERE NOT EXISTS (
  SELECT 1 FROM `menus` WHERE `path` = '/generated/department'
);
