-- Code generated by modulegen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS `departments` (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `manager` VARCHAR(255) NULL,
  `status` INT NOT NULL,
  `created_at` DATETIME(3) NULL,
  `updated_at` DATETIME(3) NULL
);
