#!/usr/bin/env node
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

const projectRoot = process.cwd()
const args = process.argv.slice(2)

function getArg(name, fallback = '') {
  const i = args.indexOf(name)
  if (i === -1) return fallback
  return args[i + 1] ?? fallback
}

const specPath = path.resolve(projectRoot, getArg('--spec', 'specs/modules/department.module.spec.json'))
const apply = args.includes('--apply')
const confirmOverwrite = args.includes('--confirm-overwrite')

function toPascal(raw) {
  return raw
    .split(/[_-]/)
    .map((x) => x.charAt(0).toUpperCase() + x.slice(1))
    .join('')
}

function toSnake(raw) {
  return raw
    .replace(/([A-Z])/g, '_$1')
    .replace(/[-\s]/g, '_')
    .toLowerCase()
    .replace(/^_/, '')
}

function mapGoType(type) {
  if (type === 'int') return 'int'
  if (type === 'bool') return 'bool'
  if (type === 'datetime') return 'time.Time'
  return 'string'
}

function mapGoPointerType(type) {
  return `*${mapGoType(type)}`
}

function mapTsType(type) {
  if (type === 'int') return 'number'
  if (type === 'bool') return 'boolean'
  if (type === 'datetime') return 'string'
  return 'string'
}

function validateSpec(spec) {
  if (!spec || typeof spec !== 'object') throw new Error('invalid spec file')
  if (!spec.moduleName || !/^[a-z][a-z0-9_]*$/.test(spec.moduleName)) throw new Error('invalid moduleName')
  if (!spec.displayName) throw new Error('missing displayName')
  if (!Array.isArray(spec.fields) || spec.fields.length === 0) throw new Error('fields must not be empty')
}

function renderGoModel(spec) {
  const modelName = toPascal(spec.moduleName)
  const fields = spec.fields
    .map((f) => `\t${toPascal(f.name)} ${mapGoType(f.type)} \`json:"${f.name}" gorm:"column:${toSnake(f.name)}"\``)
    .join('\n')

  return `package ${spec.moduleName}

import "time"

// Code generated by modulegen. DO NOT EDIT.
type ${modelName} struct {
\tID uint \`json:"id" gorm:"primaryKey"\`
${fields}
\tCreatedAt time.Time \`json:"createdAt"\`
\tUpdatedAt time.Time \`json:"updatedAt"\`
}
`
}

function renderGoHandler(spec) {
  const modelName = toPascal(spec.moduleName)
  const createFields = spec.fields
    .map((f) => `\t${toPascal(f.name)} ${mapGoType(f.type)} \`json:"${f.name}"${f.required ? ' binding:"required"' : ''}\``)
    .join('\n')
  const updateFields = spec.fields
    .map((f) => `\t${toPascal(f.name)} ${mapGoPointerType(f.type)} \`json:"${f.name}"\``)
    .join('\n')
  const updateMap = spec.fields
    .map((f) => `\tif req.${toPascal(f.name)} != nil {\n\t\tupdates["${toSnake(f.name)}"] = *req.${toPascal(f.name)}\n\t}`)
    .join('\n')

  return `package ${spec.moduleName}

import (
\t"net/http"
\t"strconv"

\t"github.com/gin-gonic/gin"
\t"github.com/liusheng/tencent-admin-starter/apps/api/internal/response"
\t"gorm.io/gorm"
)

// Code generated by modulegen. DO NOT EDIT.
type Handler struct {
\tdb *gorm.DB
}

type createRequest struct {
${createFields}
}

type updateRequest struct {
${updateFields}
}

func NewHandler(db *gorm.DB) *Handler {
\treturn &Handler{db: db}
}

func (h *Handler) List(c *gin.Context) {
\tpage := 1
\tsize := 10
\tif p, err := strconv.Atoi(c.DefaultQuery("page", "1")); err == nil && p > 0 {
\t\tpage = p
\t}
\tif s, err := strconv.Atoi(c.DefaultQuery("size", "10")); err == nil && s > 0 {
\t\tsize = s
\t}
\toffset := (page - 1) * size

\tquery := h.db.Model(&${modelName}{})
\tvar total int64
\tif err := query.Count(&total).Error; err != nil {
\t\tc.JSON(http.StatusInternalServerError, response.Error("query failed"))
\t\treturn
\t}

\tvar list []${modelName}
\tif err := query.Order("id DESC").Offset(offset).Limit(size).Find(&list).Error; err != nil {
\t\tc.JSON(http.StatusInternalServerError, response.Error("query failed"))
\t\treturn
\t}

\tc.JSON(http.StatusOK, response.Success(response.PageData{
\t\tList: list,
\t\tTotal: total,
\t\tPage: page,
\t\tSize: size,
\t}))
}

func (h *Handler) Create(c *gin.Context) {
\tvar req createRequest
\tif err := c.ShouldBindJSON(&req); err != nil {
\t\tc.JSON(http.StatusBadRequest, response.Error("invalid payload"))
\t\treturn
\t}

\tentity := ${modelName}{
${spec.fields.map((f) => `\t\t${toPascal(f.name)}: req.${toPascal(f.name)},`).join('\n')}
\t}
\tif err := h.db.Create(&entity).Error; err != nil {
\t\tc.JSON(http.StatusBadRequest, response.Error("create failed"))
\t\treturn
\t}
\tc.JSON(http.StatusOK, response.Success(entity))
}

func (h *Handler) Update(c *gin.Context) {
\tid, err := strconv.Atoi(c.Param("id"))
\tif err != nil {
\t\tc.JSON(http.StatusBadRequest, response.Error("invalid id"))
\t\treturn
\t}
\tvar req updateRequest
\tif err := c.ShouldBindJSON(&req); err != nil {
\t\tc.JSON(http.StatusBadRequest, response.Error("invalid payload"))
\t\treturn
\t}
\tupdates := map[string]interface{}{}
${updateMap}
\tif len(updates) == 0 {
\t\tc.JSON(http.StatusBadRequest, response.Error("no fields to update"))
\t\treturn
\t}
\tif err := h.db.Model(&${modelName}{}).Where("id = ?", id).Updates(updates).Error; err != nil {
\t\tc.JSON(http.StatusInternalServerError, response.Error("update failed"))
\t\treturn
\t}
\tvar entity ${modelName}
\tif err := h.db.First(&entity, id).Error; err != nil {
\t\tc.JSON(http.StatusNotFound, response.Error("not found"))
\t\treturn
\t}
\tc.JSON(http.StatusOK, response.Success(entity))
}

func (h *Handler) Delete(c *gin.Context) {
\tid, err := strconv.Atoi(c.Param("id"))
\tif err != nil {
\t\tc.JSON(http.StatusBadRequest, response.Error("invalid id"))
\t\treturn
\t}
\tif err := h.db.Delete(&${modelName}{}, id).Error; err != nil {
\t\tc.JSON(http.StatusInternalServerError, response.Error("delete failed"))
\t\treturn
\t}
\tc.JSON(http.StatusOK, response.Success(gin.H{"id": id}))
}
`
}

function renderSql(spec) {
  const cols = spec.fields
    .map((f) => {
      let sqlType = 'VARCHAR(255)'
      if (f.type === 'int') sqlType = 'INT'
      if (f.type === 'bool') sqlType = 'TINYINT(1)'
      if (f.type === 'datetime') sqlType = 'DATETIME(3)'
      return `  \`${toSnake(f.name)}\` ${sqlType} ${f.required ? 'NOT NULL' : 'NULL'}`
    })
    .join(',\n')

  return `-- Code generated by modulegen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS \`${toSnake(spec.moduleName)}s\` (
  \`id\` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
${cols},
  \`created_at\` DATETIME(3) NULL,
  \`updated_at\` DATETIME(3) NULL
);
`
}

function renderTsApi(spec) {
  const typeName = toPascal(spec.moduleName)
  const fields = spec.fields.map((f) => `  ${f.name}: ${mapTsType(f.type)}`).join('\n')
  return `import http from '../../api/http'
import type { ApiResponse, PageData } from '../../types'

// Code generated by modulegen. DO NOT EDIT.
export interface ${typeName}DTO {
  id: number
${fields}
  createdAt: string
  updatedAt: string
}

export async function list${typeName}(page = 1, size = 10, keyword = '') {
  const { data } = await http.get<ApiResponse<PageData<${typeName}DTO>>>(\`/api/${spec.moduleName}s\`, {
    params: { page, size, keyword: keyword || undefined }
  })
  return data.data
}

export async function create${typeName}(payload: Partial<${typeName}DTO>) {
  const { data } = await http.post<ApiResponse<${typeName}DTO>>(\`/api/${spec.moduleName}s\`, payload)
  return data.data
}

export async function update${typeName}(id: number, payload: Partial<${typeName}DTO>) {
  const { data } = await http.put<ApiResponse<${typeName}DTO>>(\`/api/${spec.moduleName}s/\${id}\`, payload)
  return data.data
}

export async function delete${typeName}(id: number) {
  await http.delete(\`/api/${spec.moduleName}s/\${id}\`)
}
`
}

function renderVueList(spec) {
  const typeName = toPascal(spec.moduleName)
  const columns = spec.fields.map((f) => `{ colKey: '${f.name}', title: '${f.label}' }`).join(',\n  ')
  return `<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { list${typeName}, type ${typeName}DTO } from './api.generated'

const data = ref<${typeName}DTO[]>([])
const loading = ref(false)
const page = ref(1)
const size = ref(10)
const total = ref(0)

const columns = [
  { colKey: 'id', title: 'ID' },
  ${columns}
]

async function loadData() {
  loading.value = true
  try {
    const res = await list${typeName}(page.value, size.value)
    data.value = res.list
    total.value = res.total
  } finally {
    loading.value = false
  }
}

onMounted(loadData)
</script>

<template>
  <div class="page-card">
    <t-typography-title :level="4" style="margin: 0 0 12px">${spec.displayName}（生成示例）</t-typography-title>
    <div class="data-table-wrap">
      <t-table row-key="id" :data="data" :columns="columns" :loading="loading" bordered />
    </div>
    <div style="margin-top: 12px; display: flex; justify-content: flex-end">
      <t-pagination v-model:current="page" v-model:page-size="size" :total="total" @change="loadData" />
    </div>
  </div>
</template>
`
}

async function readMaybe(filePath) {
  try {
    return await readFile(filePath, 'utf8')
  } catch {
    return null
  }
}

async function ensureDir(filePath) {
  await mkdir(path.dirname(filePath), { recursive: true })
}

async function main() {
  const specRaw = await readFile(specPath, 'utf8')
  const spec = JSON.parse(specRaw)
  validateSpec(spec)

  const moduleName = spec.moduleName
  const generatedTargets = [
    {
      path: path.resolve(projectRoot, `apps/api/internal/generated/${moduleName}/model.generated.go`),
      content: renderGoModel(spec)
    },
    {
      path: path.resolve(projectRoot, `apps/api/internal/generated/${moduleName}/handler.generated.go`),
      content: renderGoHandler(spec)
    },
    {
      path: path.resolve(projectRoot, `apps/api/migrations/zz_generated_${moduleName}.sql`),
      content: renderSql(spec)
    },
    {
      path: path.resolve(projectRoot, `apps/web/src/generated/${moduleName}/api.generated.ts`),
      content: renderTsApi(spec)
    },
    {
      path: path.resolve(projectRoot, `apps/web/src/generated/${moduleName}/ListView.generated.vue`),
      content: renderVueList(spec)
    }
  ]

  const plan = []
  for (const item of generatedTargets) {
    const existing = await readMaybe(item.path)
    let action = 'create'
    let conflict = false
    if (existing !== null) {
      if (existing === item.content) action = 'noop'
      else {
        action = 'update'
        conflict = true
      }
    }
    plan.push({ ...item, action, conflict })
  }

  console.log(`\n[ModuleGen] spec: ${path.relative(projectRoot, specPath)}`)
  for (const item of plan) {
    console.log(`- ${item.action.toUpperCase()} ${path.relative(projectRoot, item.path)}${item.conflict ? ' (conflict)' : ''}`)
  }

  const conflicts = plan.filter((x) => x.conflict).length
  if (!apply) {
    console.log('\n[ModuleGen] dry-run finished. Re-run with --apply --confirm-overwrite to write files.')
    return
  }

  if (conflicts > 0 && !confirmOverwrite) {
    throw new Error('conflicts detected: pass --confirm-overwrite to apply updates')
  }

  let written = 0
  for (const item of plan) {
    if (item.action === 'noop') continue
    await ensureDir(item.path)
    await writeFile(item.path, item.content, 'utf8')
    written += 1
  }
  console.log(`\n[ModuleGen] apply finished. files written: ${written}`)
}

await main().catch(async (err) => {
  console.error(`[ModuleGen] ${err.message}`)
  try {
    const s = await stat(specPath)
    if (s.isDirectory()) {
      console.error('[ModuleGen] --spec must be a file, not directory.')
    }
  } catch {}
  process.exit(1)
})
